// Code generated by "stringer -type=TokenType -linecomment -output token_type_string.go"; DO NOT EDIT.

package tokenizer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenTypeNull-0]
	_ = x[TokenTypeTrue-1]
	_ = x[TokenTypeFalse-2]
	_ = x[TokenTypeLiteral-3]
	_ = x[TokenTypeQuotedLiteral-4]
	_ = x[TokenTypeQuotedEscapedLiteral-5]
	_ = x[TokenTypeObjectStart-6]
	_ = x[TokenTypeObjectEnd-7]
	_ = x[TokenTypeArrayStart-8]
	_ = x[TokenTypeArrayEnd-9]
	_ = x[TokenTypeEOF-10]
}

const _TokenType_name = "nulltruefalseliteralquoted_literalquoted_escaped_literal{}[]eof"

var _TokenType_index = [...]uint8{0, 4, 8, 13, 20, 34, 56, 57, 58, 59, 60, 63}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
