[package]
name = "fastjson"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "fastjson"
path = "lib.rs"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
